<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Feedback;
use App\Notification;
class FeedbackController extends Controller
{

    public function create(Request $req,$transactionid,$shopid)
    {
        //return "Test:".$transactionid." + ".$shopid;

        //$transaction = Transaction::find($transactionid);
        $data = $req->all();
        $user = Auth::user();

     
        $feed = Feedback::create([
            "shop_id" => $shopid,
            "user_id" => $user->id,
            "transaction_id" => $transactionid,
            "rate" => $data["rate"],
            "comment" => $data["comment"]

        ]);
        
        //notify user & shop owner
        Notification::create([
            "sender_id" => $feed->shop->user_id,
            "receiver_id" => $user->id,
            "title" => "Thanks for your feedback for your transaction: ".$transactionid,
            "body" => "Thanks for your feedback for your transaction: ".$transactionid.", your feedback is now collected by the system, thank you!"
        ]);
        Notification::create([
            "sender_id" => $user->id,
            "receiver_id" => $feed->shop->user_id,
            "title" => "You got an feedback from customer".$user->name ."for transaction id: ".$transactionid,
            "body" => "You got an feedback from customer".$user->name ."for transaction id: ".$transactionid." you may check it on your shop comments page.&nbsp; this message is automatic generated by the system, if there is abuse of use please contact us."
        ]);


        return view("ucp.feedback.ok");
        
    }


}
